---
- name: CI/CD Rules
  hosts: all
  sources:
    - name: azure_service_bus
      azure_service_bus:
        conn_str: "{{connection_str}}"
        queue_name: "{{queue_name}}"
  rules:
    - name: save last event
      condition: +payload
      action:
        assert_fact:
          fact:
            last_event: "{{event}}"
    - name: save fact
      condition: +last_event
      action:
        none:
...
