---
- name: CI/CD Rules
  hosts: all
  sources:
    - name: azure_service_bus
      azure_service_bus:
        conn_str: "{{connection_str}}"
        queue_name: "{{queue_name}}"
  rules:
    - name: debug messages
      condition: +payload
      action:
        debug:
...
