---
- name: Local Deploy Git Hook Rules
  hosts: all
  sources:
    - name: webhook
      webhook:
        port: 5001
  rules:
    - name: debug messages
      condition: +payload
      action:
        debug:
    - name: run tests 1
      condition: payload.repo == "{{repo}}"
      action:
        run_playbook:
          name: run_deploy.yml
          var_root: payload
          post_events: true
    - name: print output
      condition: +output
      action:
        print_event:
          var_root: output
...
