---
- name: Local Test Runner Git Hook Rules
  hosts: all
  sources:
    - name: webhook
      webhook:
  rules:
    - name: run tests 1
      condition: event.payload.src_path == "{{src_path}}"
      action:
        run_playbook:
          name: run_pytest.yml
          var_root: payload
          post_events: true
    - name: print output
      condition: event.output is defined
      action:
        print_event:
          var_root: output
...
