---
- name: Local Deploy Git Hook Rules
  hosts: all
  sources:
    - name: webhook
      webhook:
        port: 5001
  rules:
    - name: run tests 1
      condition: event.payload.repo == "{{repo}}"
      action:
        run_playbook:
          name: continuous_integration.yml
          var_root: payload
          post_events: true
    - name: print output
      condition: event.output is defined
      action:
        print_event:
          var_root: output
...
