---
- name: GitHub Deploy Git Hook Rules
  hosts: all
  sources:
    - name: azure_service_bus
      azure_service_bus:
        conn_str: "{{connection_str}}"
        queue_name: "{{queue_name}}"
  rules:
    - name: debug messages
      condition: payload is defined
      action:
        debug:
    - name: extract values
      condition: payload.repository.full_name == "{{repo}}"
      action:
        post_event:
          fact:
            repository_name: "{{event.payload.repository.full_name}}"
            repository_url: "{{event.payload.repository.clone_url}}"
            after: "{{event.payload.after}}"
    - name: run tests 1
      condition: repository_name == "{{repo}}"
      action:
        run_playbook:
          name: run_deploy.yml
          var_root: payload
          post_events: true
    - name: print output
      condition: output is defined
      action:
        print_event:
          var_root: output
...
