---
- name: GitHub Deploy Git Hook Rules
  hosts: all
  sources:
    - name: azure_service_bus
      azure_service_bus:
        conn_str: "{{connection_str}}"
        queue_name: "{{queue_name}}"
  rules:
    - name: extract values
      condition: event.payload.repository.full_name == "{{repo_name}}"
      action:
        post_event:
          fact:
            repository_name: "{{event.payload.repository.full_name}}"
            repo: "{{event.payload.repository.clone_url}}"
            ref: "{{event.payload.after}}"
    - name: run tests 1
      condition: event.repository_name == "{{repo_name}}"
      action:
        run_playbook:
          name: run_deploy.yml
          post_events: true
    - name: print output
      condition: event.output is defined
      action:
        print_event:
          var_root: output
...
