---
- hosts: localhost
  gather_facts: False
  tasks:
    - name: checkout code
      git:
        repo: "{{repo}}"
        dest: /tmp/deploy
        version: "{{ref}}"
        update: true
        force: true
    - name: install code
      pip:
        virtualenv: /tmp/deploy/.venv
        chdir: /tmp/deploy
        editable: true
        name: .
    - name: install test code
      pip:
        virtualenv: /tmp/deploy/.venv
        chdir: /tmp/deploy
        requirements: requirements_dev.txt
    - name: run tests
      shell:
        cmd: /tmp/deploy/.venv/bin/pytest -v
        chdir: /tmp/deploy
...
